- name: Download asdf-vm
  ansible.builtin.get_url:
    url: https://github.com/asdf-vm/asdf/releases/download/v0.16.4/asdf-v0.16.4-linux-arm64.tar.gz
    dest: /tmp/asdf.tar.gz
    mode: 0644

- name: Extract asdf-vm
  ansible.builtin.unarchive:
    src: /tmp/asdf.tar.gz
    dest: /usr/local/bin/asdf
    user: deployer
    group: deployer
    mode: 0755

- name: Check if asdf-vm is installed
  ansible.builtin.shell: asdf --version
  register: asdf_version
  ignore_errors: true
